name: ds_modeller
dependencies:
- python=3.7
- pip
- pip:
  - absl-py==0.4.1
  - astor==0.7.1
  - certifi==2018.8.24
  - click==7.1.2
  - Cython==0.29.21
  - databricks-connect==8.1.9
  - gast==0.4.0
  - grpcio==1.12.1
  - h5py==2.8.0
  - joblib==0.14.1
  - Markdown==2.6.11
  - nltk==3.5
  - protobuf==3.6.0
  - py4j==0.10.9
  - pystan==2.19.1.1
  - python-dateutil==2.8.1
  - pytz==2020.1
  - PyYAML==3.13
  - regex==2018.8.29
  - scipy==1.2.1
  - six==1.15.0
  - termcolor==1.1.0
  - tqdm==4.49.0
  - Werkzeug==1.0.1
  - xmlrunner
  - nose
  - mock


